[workspace]

[package]
name = "late_check"
version = "0.1.0"
edition = "2024"

[dependencies]
rhdl = { version = "0.1.0", path = "/Users/samitbasu/Devel/rhdl/crates/rhdl" }

[dev-dependencies]
env_logger = "0.11.8"
miette = "7.6.0"
