[package]
name = "rhdl-fpga"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.79"

rhdl = { path = "../rhdl" }
strum = { version = "0.25.0", features = ["derive"] }
